project:
  type: book
  output-dir: _book

book:
  # book
  title: Naive Set Theory
  author:
    - name:
        given: Paul Richard 
        family: Halmos
        literal: Paul R. Halmos
      # Arbitrary metadata: position
      # https://quarto.org/docs/journals/authors.html#arbitrary-metadata
      position: Professor of Mathematics
      affiliations:
        - name: University of Michigan
  cover-image: images/cover_halmos_naive_set_theory.png
  downloads: [pdf]
  favicon: images/favicon_halmos_naive_set_theory.ico
  repo-url: https://github.com/luifrancgom/halmos_naive_set_theory_quarto/
  issue-url: https://github.com/luifrancgom/halmos_naive_set_theory_quarto/issues
  repo-actions: [edit, source, issue]
  reader-mode: true
  chapters:
    - index.qmd
    - preface.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - chapter_5.qmd
    - chapter_6.qmd
    - chapter_7.qmd
    - chapter_8.qmd
    - chapter_9.qmd
    - chapter_10.qmd
    - chapter_11.qmd
    - chapter_12.qmd
    - chapter_13.qmd
    - chapter_14.qmd
    - chapter_15.qmd
    - chapter_16.qmd
    - chapter_17.qmd
    - chapter_18.qmd
    - chapter_19.qmd
    - chapter_20.qmd
    - chapter_21.qmd
    - chapter_22.qmd
    - chapter_23.qmd
    - chapter_24.qmd
    - chapter_25.qmd
    - references.qmd

format:
  html:
    # table of contents
    toc: true
    toc-location: right
    # rendering
    embed-resources: false
    # format options
    theme:
      - cosmo
      - scss/custom.scss
    html-math-method: mathjax
    # includes
    include-in-header: 
      - file: partials/html/header.html
  pdf:
    # format options
    pdf-engine: xelatex
    # table of contents
    # Trick to move the table of contents after the prefaces
    # See https://github.com/orgs/quarto-dev/discussions/9839
    toc: false
    # fonts
    fontsize: 12pt
    # colors
    linkcolor: blue
    citecolor: blue
    urlcolor: blue
    colorlinks: true
    # layout
    documentclass: scrbook
    classoption: [headsepline=true, pagesize=auto]
    papersize: b5
    indent: true
    # references
    link-citations: true
    link-bibliography: true
    # includes
    include-in-header: 
      - file: partials/latex/header.tex
    include-after-body: 
      - file: partials/latex/after-body.tex
    # rendering
    template: partials/latex/template.tex
    template-partials:
      - partials/latex/title.tex
      - partials/latex/before-body.tex
    # keep-md: true
    # keep-tex: true

# citations
bibliography: references/halmos_naive_set_theory_quarto.bib
csl: references/apa_7ed.csl 

# Partial solution to include axioms
crossref:
  cnj-title: Axiom
  cnj-prefix: Axiom
  cnj-labels: arabic

engine: knitr
editor: source
